import dotenv from 'dotenv';
dotenv.config();

import { StringOutputParser } from "@langchain/core/output_parsers";
import { TavilySearchResults } from '@langchain/community/tools/tavily_search';
import { ChatGroq } from '@langchain/groq';
import { ChatPromptTemplate } from '@langchain/core/prompts';
import { RunnableSequence, RunnableLambda } from '@langchain/core/runnables';

const tool = new TavilySearchResults({ maxResults: 5 });

const llm = new ChatGroq({
  model: "mistral-saba-24b",
  temperature: 0.5,
});

const prompt = ChatPromptTemplate.fromTemplate(
    'Analyse this prompt as best as you can: {input}. ' +
    'Your goal is to generate a well-structured query for use in retrieval and/or web search.' +
    'Return only the web search query with no additional formatting or text.'
  );

const web_search = RunnableLambda.from(
  async (llm_output) => {
    console.log('This is the query generated by the LLM:', llm_output);
    const web_results = await tool.invoke({
      input: llm_output
    });
    const parsed = typeof web_results === "string" ? JSON.parse(web_results) : web_results;
    parsed.forEach((search) => {
        console.log(search.title);
        console.log(search.url);
        console.log(search.content);
        console.log("\n------------------------------------------------------\n");
      });
  
  }
);

const parser = new StringOutputParser()

const chain = RunnableSequence.from([
  prompt,
  llm,
  parser,
  web_search
]);

const response = await chain.invoke({
  input: 'I want to fix my refrigerator, what is the best you can offer me?'
});


